
# This is a basic workflow to help you get started with Actions

name: test-jp-app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ PROD ]
  pull_request:
    branches: [ PROD ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
##jobs:
##  
##   build:
##     runs-on: ubuntu-latest
##     steps:
##       - uses: actions/checkout@v3
##         name: Use Node.js ${{ matrix.node-version }}
##       - uses: actions/setup-node@v1
##         with: 
##          node-version: ${{ matrix.node-version }}
##       - run: yarn install
##       - run: yarn build
##      name: DigitalOcean Spaces Action
##on:
##  push:
##    paths: ./pages

#=================================================
#
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@master
#    - uses: LibreTexts/do-space-sync-action@master
#      with:
#        args: --acl public-read
#      env:
#        SOURCE_DIR: './pages'
#        DEST_DIR: 'Testing-Folder'
#        SPACE_NAME: ${{ secrets.DO_NAME }}
#        SPACE_REGION: ${{ secrets.DO_REGION}}
#        SPACE_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS }}
#        SPACE_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET }}
        



    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.2.0
      with:
        #provider: DO # default is linode
        region: ${{ secrets.DO_REGION}}
        access_key: ${{ secrets.DO_ACCESS }}
        secret_key: ${{ secrets.DO_SECRET }}

    - name: Interact with object storage
      run: |
        s3cmd sync ./ s3://github-test1.sfo3.digitaloceanspaces.com
        s3cmd get Testing-Folder/api/hello.js hello.js
        s3cmd info s3://github-test1.sfo3.digitaloceanspaces.com













        
        
          
          
          
 #     # - name: Server sync 
 #    #    uses: burnett01/rsync-deployments@4.0
 #   #     with:
 #  #       switches: -avzr --exclude=".git" --include="./node_nodules/" --include="./public/" --include="*.json"=""
 # #        path: /
 ##         remote_path: /root/home/nextjs-jpsblog
 ##         remote_host: ${{ secrets.PROD_HOST }}
 ##         remote_port: ${{ secrets.PORT }}
 ##         remote_user: ${{ secrets.USERNAME }}
 ##         remote_key: ${{ secrets.PRIVATEKEY }}
      
 #   #   - name: Server application start
 #   #     uses: appleboy/ssh-action@master
 #   #     with:
 #   #      host: ${{ secrets.PROD_HOST }}
 #   #      username: ${{ secrets.USERNAME }}
 #   #      key: ${{ secrets.PRIVATEKEY }}
 #   #      port: ${{ secrets.PORT }}
 #    #     script: |
 #    #       cd /root/home/nextjs-jpsblog
 #    #       pm2 start yarn --name "nextjs" --interpreter bash -- star
 #    # 
 #   #   - name: Send mail notification
 #   #     uses: dawidd6/action-send-mail@v3
 #   #     with:
 #   #      server_address: ${{secrets.EMAIL_SMTP}}
 #   #      server_port: ${{secrets.EMAIL_PORT}}
 #   #      username: ${{secrets.MAIL_USERNAME}}
 #   #      password: ${{secrets.MAIL_PASSWORD}}
 #   #      subject: Maniak Devops Challenge job result (PROD)
 #   #      to: angel@butchershop.co
 #   #      from: JP Gomez 
 #   #  
      
